stages:
  - test
  - build
  - beta

cache:
  key:
    files:
      - Gemfile.lock
  paths:
    - vendor/bundle

before_script:
  - |
    if ! rbenv versions | grep -q "$(cat .ruby-version)"; then
      apt-get update -qq && apt-get install -y -qq libffi-dev libyaml-dev
      rbenv install $(cat .ruby-version) || true
    fi
  - rbenv global $(cat .ruby-version) || true
  - bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs $(nproc)

test:
  image: fabernovel/android:api-34-v1.10.1
  stage: test
  script:
    - bundle exec fastlane test

build:
  image: fabernovel/android:api-34-v1.10.1
  stage: build
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './'
  script:
    - apt update -y && apt install -y curl
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - bundle exec fastlane build
  artifacts:
    paths:
      - app/build/outputs/bundle/release/app-release.aab

beta:
  image: fabernovel/android:api-34-v1.10.1
  stage: beta
  script:
    - bundle exec fastlane beta
  when: manual
  allow_failure: true
  only:
    refs:
      - main

variables:
  KUBERNETES_MEMORY_REQUEST: 2Gi
  KUBERNETES_MEMORY_LIMIT: 2Gi